variables: &variables
  SFOS_VERSION: 4.1.0.24
  BUILD_PATH: /home/mersdk/harbour-sailfin

stages:
  - lint
  - build

image: coderus/sailfishos-platform-sdk:$SFOS_VERSION
default:
  before_script:
    - cp -a . $BUILD_PATH && cd $BUILD_PATH

lint:sfos:qmllint:
  stage: lint
  script:
    - sudo zypper --non-interactive install qt5-qtdeclarative-devel-tools
    - cd sailfish/qml
      # Find all files ending in .qml or .js and pass them as arguments to qmllint
    - find -type f \( -name \*.qml -o -name \*.js \) -exec /usr/lib/qt5/bin/qmllint \{\} + 
  allow_failure: true

.build:sfos: &build
  stage: build
  artifacts:
    paths:
      - $BUILD_PATH/RPMS/
  script:
    - mb2 -t SailfishOS-$SFOS_VERSION-$MER_ARCH build

build:sfos:armv7hl:
  variables:
    <<: *variables
    MER_ARCH: armv7hl
  <<: *build

build:sfos:aarch64:
  variables:
    <<: *variables
    MER_ARCH: aarch64
  <<: *build
